platform :ios, ‘8.0’
use_frameworks!
def pods
    
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'TMCache'
    pod 'FMDB'
    pod 'BaiduMapKit'
    pod 'IQKeyboardManager'
    pod 'FLAnimatedImage', '~> 1.0'
    pod 'JPush'
    pod 'Charts'
end

target 'AnYiYun' do
    
    pods
    
end
