platform :ios, ‘8.0’

def pods
    
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'TMCache'
    pod 'FMDB'
    pod 'BaiduMapKit'
    pod 'IQKeyboardManager'
end

target 'AnYiYun' do
    
    pods
    
end
